### ISSUE TITLE
Builder fails?

### ISSUE THREAD

**Issue by SManAT** [valueerrorx/life-builder#4]
Testet several times to create a ISO File.
Never got it.
After some Time Builder hangs.
Dont know where to dig deeper to provide more information.
Inside the build directory i got a lot of files ....
Any tipps?

**Comment by valueerrorx** [comment]
first i need to know on what operating system you tried to build.  building on "live usb" installations won't work.. it needs to be an installed system.   kubuntu 18.04 or something very similar.

to figure out what the problem is  just start the builder from the command line.. you will see all error messages there...

run 

```sudo python3 builder ```

**Comment by SManAT** [comment]
Ah OK it was an LIVE System. 
I'll try to do that on instlled System.
Now I'm Using Kubuntu 16.04.

I think we can close that issue.
Tx!

**Comment by valueerrorx** [comment]
building from a live system (or persistent system) is actually a cool idea..  you could alter the system, change branding, install/remove software and then rebuild the iso file and burn it on another flashdrive..


in theory building on a live system "could" work because the builder does not know about the underlying overlayfs ... and it shouldn't need to...

but the only time i accidentially started a build on a live system it didn't work out because you need A LOT of space and my flashdrive and therefore the whole process was so slow - it made me suspicious 


@free space:
almost the whole system is copied to the workdirectory to /home/lifebuilder/lifebuilder/dummysys
then a filesystem.squashfs is created out of this dummysys + several folders that need no changes
then the ISO filestructure is generated with all the necessary files and and the file life.iso is created.

so you need at least 15 GB of free space on your flashdrive AND a very fast flashdrive - otherwise it will take hours instead of 20 min or less... 

you could of course mount an SSD and tell "lifebuilder" to use the SSD as "Workdirectory" (setting is found under the "advanced" tab)

**Comment by SManAT** [comment]
Well, i tried therefore an NFS Network Share with a enough space.
But even not working. Actually im using a full installed system, and we will see .... :)

**Comment by SManAT** [comment]
just finishing testing on a VirtualBox installed System
Works like a charme ;)
